name: 'HuskChat'
version: '${version}'
description: '${description}'
author: 'William278'
main: 'net.william278.huskchat.BukkitHuskChat'
api-version: 1.17
folia-supported: true
softdepend:
  - 'LuckPerms'
  - 'PlaceholderAPI'
  - 'Spicord'